x = input('Enter your first variable:\n')
y = input('Enter your second variable:\n')
sum = int(x)+int(y)
diff = int(x)-int(y)
prod = int(x)*int(y)
print('Your first variable: ' + x + '\n')
print('Your second variable: ' + y + '\n')
print('Summation: ' + str(sum) + '\n')
print('Difference: ' + str(diff) + '\n')
print('Multiplication: ' + str(prod) + '\n')
